<a href="https://colab.research.google.com/github/Pham-Hoang-Quan/Lab_ML/blob/main/Lab1_20130373_PhamHoangQuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1.1

In [ ]:
def task1():
  n = int(input("Enter n : "))
  L = []
  for i in range(n):
    L.append(int(input("enter ni: ")))
  print("L's elements",L)


  max = L[0]
  for n in L:
    if n > max:
      max = n
  print("Max: ", max)

  min = L[0]
  for n in L:
    if n < min:
      min = n
  print("Min: ", min)

  sum = 0
  for n in L:
    sum += n
  print("Sum: ", sum)

  L.sort()
  print("Sorted list (ascending order):", L)

  pos = 0
  neg = 0
  for x in L:
    if x > 0:
      pos += 1
    elif x < 0:
      neg += 1
  print("Positive numbers: ", pos)
  print("Negative numbers: ", neg)



task1()




Enter n : 3
enter ni: 12
enter ni: 6
enter ni: 2
L's elements [12, 6, 2]
Max:  12
Min:  2
Sum:  20
Sorted list (ascending order): [2, 6, 12]
Positive numbers:  3
Negative numbers:  0


Task 1.2

In [ ]:
def task1_2(n):
  sum = 0
  if n > 0:
    for x in range(n):
      for y in range(n):
        sum += x*y

  return sum

print(task1_2(5))



100


Task 1.3

In [ ]:
class Account:
  def __init__(self, name, email, country):
    self.__name = name
    self.__email = email
    self.__country = country
    self.friends = list()
    self.posts = list()

  def count_posts(self):
    return len(self.posts)

  def add_post(self, post):
    self.posts.append(post)

  def add_friend(self, account):
    self.friends.append(account)

  def getMaxLikePostByFriend(self):
    max_like = 0
    max_acc = None
    for acc in self.friends:
      for post in acc.posts:
        if post.get_likes() > max_like:
          max_like = post.get_likes()
          max_acc = acc
    return max_acc.get_name()

  def get_name(self):
        return self.__name

  def get_country(self):
        return self.__country

  def get_info(self):
    return self.__name, self.__email, self.__country

class Post:
  def __init__(self, content, subject, likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes

  def get_likes(self):
    return self.__likes

  def get_info(self):
    return self.__content, self.__subject, self.__likes


class AccountManager:
  def __init__(self):
    self.__accounts = list()

  def add_Account(self, acc):
    self.__accounts.append(acc)


  def groupAccountsByPostLike(self):
    group_acc = dict()
    for acc in self.__accounts:
      if len(acc.posts) < 10:
        group_acc[acc.get_name()] = False
      else:
        group_acc[acc.get_name()] = True
    return group_acc

  def filterAccount(self, country):
    accs = list()
    for acc in self.__accounts:
      if acc.get_country() == country:
        accs.append(acc)
    sorted_accs = sorted(accs, key=lambda acc: (acc.count_posts(), acc.get_name()))
    return sorted_accs

class VerifiedAccount(Account):
    def __init__(self, name, email, country, fromdate):
        super().__init__(name, email, country)
        self.fromdate = fromdate

class NormalProduct(Account):
    def __init__(self, name, email, country, ):
        super().__init__(name, email, country)


# test

acc_quan = Account("Quân", "quan@gmail.com", "VietNam")
acc_tien = Account("Tiên", "tien@gmail.com", "VietNam")
acc_nhu = Account("Như", "nhu@gmail.com", "VietNam")

acc_ver1 = VerifiedAccount("Quân", "quan@gmail.com", "VietNam", "123")

post1 = Post("post1", "ok", 6)
post2 = Post("post2", "ok", 9)
post3 = Post("post3", "ok", 10)
post4 = Post("post3", "ok", 20)

acc_tien.add_post(post1)
acc_tien.add_post(post2)
acc_nhu.add_post(post3)
acc_tien.add_post(post4)


acc_quan.add_friend(acc_tien)
acc_quan.add_friend(acc_nhu)
acc_tien.add_friend(acc_nhu)

acc_manager = AccountManager()
acc_manager.add_Account(acc_tien)
acc_manager.add_Account(acc_quan)
acc_manager.add_Account(acc_nhu)

print(acc_quan.getMaxLikePostByFriend())
print(acc_manager.groupAccountsByPostLike())
print([acc.get_name() for acc in acc_manager.filterAccount("VietNam")])






Tiên
{'Tiên': False, 'Quân': False, 'Như': False}
['Quân', 'Như', 'Tiên']


Task 2.1

In [ ]:
import numpy as np

arr = np.array(range(10, 26))

reversed_arr = arr[::-1]

print(reversed_arr)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2

In [ ]:
import numpy as np

def repeat_array(arr):
  print("Original array: ", arr)
  re = np.array(arr)
  for x in range(2):
    for a in arr:
      re = np.append(re, a)
    print("Repeating ", x + 2 , " times: ", re)
repeat_array([1, 2, 3, 4])


Original array:  [1, 2, 3, 4]
Repeating  2  times:  [1 2 3 4 1 2 3 4]
Repeating  3  times:  [1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3

In [ ]:
import numpy as np


def replace(arr):
  arr[arr > 0.5] = 0.5
  return arr

# test
arr = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.51, 0.34, 0.15]])
print(replace(arr))



[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
